models/Autores.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "autores".
 *
 * @property int $id
 * @property string $nombre
 * @property string $foto
 *
 * @property Libros[] $libros
 */
class Autores extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'autores';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['nombre'], 'string', 'max' => 50],
            [['foto'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['foto'], 'default', 'value' => NULL]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'foto' => 'Foto',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLibros()
    {
        return $this->hasMany(Libros::className(), ['autor_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return AutoresQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AutoresQuery(get_called_class());
    }

    public function getImageUrl($id)
    {
        return Url::to('@web/imgs/autores/' . $id.'.jpg',
            true);
    }

    public function upload()
    {
        if ($this->validate()) {
            $id = Autores::getLasId()->id +1;
            $this->foto->saveAs('imgs/autores/' . $id . '.jpg');
            return true;
        } else {
            return false;
        }
    }
    public function uploadid($id)
    {
        if ($this->validate()) {
            $this->foto->saveAs('imgs/autores/' . $id . '.jpg');
            return true;
        } else {
            return false;
        }
    }
    public function getLasId(){
        return $id=Autores::find()
            ->select('id')
            ->orderBy(['id' =>SORT_DESC])
            ->limit(1)
            ->one();
    }
    public function  editModel($model){
        $id = Autores::getLasId()->id +1;
        $model->name = $id.'.jpg';
        return $model;

    }

}

controllers/AutoresController.php
<?php

namespace app\controllers;

use app\models\Libros;
use Yii;
use app\models\Autores;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * AutoresController implements the CRUD actions for Autores model.
 */
class AutoresController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Autores::find(),
            'pagination' => [
                'pageSize' => 4
            ]

        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionList()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Autores::find(),
            'pagination' => [
                'pageSize' => 1
            ]

        ]);

        return $this->render('detail', [
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionCreate()
    {
        $model = new Autores();

        if ($model->load(Yii::$app->request->post())) {
            $model->foto = UploadedFile::getInstance($model, 'foto');
            if ($model->foto == NULL){
                $model->validate();
                $model->save();
                return $this->redirect(['show2', 'id' => $model->id]);
            }else{
                if ($model->upload()) {
                    Autores::editModel($model->foto);
                    $model->foto = $model->foto->name;
                    $model->validate();
                    $model->save();
                    return $this->redirect(['show2', 'id' => $model->id]);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->foto = UploadedFile::getInstance($model, 'foto');
            if ($model->foto == NULL){
                $model->save();
                return $this->redirect(['show2', 'id' => $model->id]);
            }else{
                if ($model->uploadid($id)) {
                    Autores::editModel($model->foto);
                    $model->foto = $id .'.jpg';
                    $model->save();
                    return $this->redirect(['show2', 'id' => $model->id]);
                }
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    protected function findModel($id)
    {
        if (($model = Autores::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    public function actionCrud()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Autores::find(),
            'pagination' => [
                'pageSize' => 4
            ]
        ]);
        return $this->render('crudAutores', [
            'dataProvider' => $dataProvider
        ]);
    }
    public function actionShow2($id)
    {
        $autores=Autores::find()
            ->where(['id' => $id])->one();

        return $this->render("detail_autor",[
            "model"=>$autores,
        ]);
    }
    public function actionShow($id)
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Libros::find()->where(['autor_id' => $id]),
            'pagination' => [
                'pageSize' => 4
            ]

        ]);

        $autor = Autores::find()
            ->select('nombre')
            ->where(['id' => $id])
            ->asArray()
            ->one();

        return $this->render('full_detail', [
            'dataProvider' => $dataProvider,
            'nombreAutor' => $autor['nombre']
        ]);
    }
}

views/autores/_detail.php
<?php
use yii\helpers\Html;
$url = $model->getImageUrl($model->id);
?>
<div class="autores-index">
    <div class="jumbotron">
        <h1><?= $model->nombre?></h1>
    </div>
    <div class="container">
        <h1></h1>
        <div class="row">
                <div class="thumbnail">
                    <?= Html::img($url, [ 'width'=>'300px',['class' => 'img-responsive img-thumbnail'] ]); ?>
                </div>
            </div>
        <div class="row center-block"><?= Html::a('Obras', ['/autores/show', 'id'=>$model->id], ['class'=>'btn btn-danger']) ?></div>
        </div>
    </div>
</div>

views/autores/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Autores */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="autores-form">

    <div class="row col-lg-6">
        <?php $form = ActiveForm::begin([
            'options' => [
                'enctype' => 'multipart/form-data',
                'validateOnSubmit' => true,
            ]]) ?>

        <?= $form->field($model, 'nombre')->textInput(['maxlength' => true, 'placeholder' => 'Introduce un autor']) ?>

        <?= $form->field($model, 'foto')->fileInput(['class' => 'btn btn-default btn-file']) ?>

        <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
    <div class="row col-lg-6">
        <?php if($model->id != NULL){
            if($model->foto == NULL ){
                $url = $model->getImageUrl(0);
            }else{
                $url = $model->getImageUrl($model->id);
            }
            ?>
            <div class="col-md-12">
                <div class="thumbnail">
                    <?= Html::img($url, ['width'=>'300px','class' =>'img-responsive']); ?>
                </div>
            </div>
            <br>
            <?php
        }
        ?>
    </div>

</div>

views/autores/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Autores */

$this->title = 'Create Autores';
$this->params['breadcrumbs'][] = ['label' => 'Autores', 'url' => ['crud']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="autores-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/autores/crudAutores.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = 'Autores';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="autores-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nuevo Autor', ['autores/create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'pager' => [
            'firstPageLabel' => 'Primera',
            'lastPageLabel'  => 'Última'
        ],
        'layout' => "{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'nombre',
            [
                'header' => 'Foto',
                'format'=>'html',
                'value' => function ($model) {
                    $url = $model->getImageUrl($model->id);
                    return Html::img($url, ['width'=>'80','height'=>'100','display' =>'block', 'margin' =>'auto']);
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/autores/detail.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: chema
 * Date: 02/04/2019
 * Time: 17:11
 */

/* @var $this yii\web\View */

use yii\widgets\ListView;
use yii\helpers\Html;

?>
<div class="site-index">
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{items}\n{pager}",
        'pager' => [
            'firstPageLabel' => 'Primera',
            'lastPageLabel'  => 'Última'
        ],
        'itemView' => '_detail',
    ]);
    ?>

</div>

views/autores/detail_autor.php
<?php

/**
 * Created by IntelliJ IDEA.
 * User: chema
 * Date: 03/04/2019
 * Time: 16:55
 */
use yii\helpers\Html;
$url = $model->getImageUrl($model->id);
/* @var $this yii\web\View */

$this->title = 'Autor';

?>
<div class="site-index">
    <div class="jumbotron">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <div class="container">
        <h1></h1>
        <div class="row">
            <div class="col-md-9">
                <div class="thumbnail">
                    <?= Html::img($url, ['width'=>'300px',['class' => 'img-responsive img-thumbnail']]); ?>
                </div>
            </div>
            <div class="col-md-3">
                <div class="thumbnail">
                    <h3>Id : <?= $model->id ?></h3>
                    <hr>
                    <h3>Nombre : <?= $model->nombre ?></h3>
                    <hr>
                    <h3>Foto Archivo : <?= $model->foto ?></h3>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

views/autores/full_detail.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;


/* @var $this yii\web\View */
$this->title = 'Autores Obras';

?>
<div class="autores-index">

    <h1><?= Html::encode($nombreAutor) ?></h1>
    <hr>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{pager}\n{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'nombre',
            'editorial',
            [
                'header' => 'Foto',
                'format'=>'html',
                'value' => function ($model) {
                    $url = $model->getImageUrl($model->id);
                    return Html::img($url, ['width'=>'80','height'=>'100','display' =>'block', 'margin' =>'auto']);
                }
            ],
        ],
    ]); ?>


</div>

views/autores/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
$this->title = 'Autores de Biblioteca';
?>
<div class="autores-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'pager' => [
            'firstPageLabel' => 'Primera',
            'lastPageLabel'  => 'Última'
        ],
        'layout' => "{pager}\n{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'nombre',
            [
                'header' => 'Foto',
                'format'=>'html',
                'value' => function ($model) {
                    $url = $model->getImageUrl($model->id);
                    return Html::img($url, ['width'=>'80','height'=>'100','display' =>'block', 'margin' =>'auto']);
                }
            ],
        ],
    ]); ?>


</div>

views/autores/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Autores */

$this->title = 'Actualizar Autores:';
$this->params['breadcrumbs'][] = ['label' => 'Autores', 'url' => ['crud']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="autores-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/autores/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Autores */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Autores', 'url' => ['crud']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

?>
<div class="autores-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'foto',
        ],
    ]) ?>

</div>