models/Libros.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "libros".
 *
 * @property int $id
 * @property string $nombre
 * @property string $editorial
 * @property int $autor_id
 * @property string $portada
 *
 * @property Autores $autor
 */
class Libros extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'libros';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'editorial', 'autor_id'], 'required'],
            [['autor_id'], 'integer'],
            [['nombre', 'editorial'], 'string', 'max' => 50],
            [['autor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Autores::className(), 'targetAttribute' => ['autor_id' => 'id']],
            [['portada'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['portada'], 'default', 'value' => NULL]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Id',
            'nombre' => 'Título',
            'editorial' => 'Editorial',
            'autor_id' => 'Autor',
            'portada' => 'Portada',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAutor()
    {
        return $this->hasOne(Autores::className(), ['id' => 'autor_id']);
    }

    /**
     * {@inheritdoc}
     * @return AutoresQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AutoresQuery(get_called_class());
    }

    public function getNombreAutor($id)
    {
        return $autor = Autores::find()->select('nombre')->where(['id'=>$id])->one();
    }
    public function getImageUrl($id)
    {
        return Url::to('@web/imgs/libros/' . $id.'.jpg',
            true);
    }
    public function upload()
    {
        if ($this->validate()) {
            $id = Libros::getLasId()->id +1;
            $this->portada->saveAs('imgs/libros/' . $id . '.jpg');
            return true;
        } else {
            return false;
        }
    }
    public function uploadid($id)
    {
        if ($this->validate()) {
            $this->portada->saveAs('imgs/libros/' . $id . '.jpg');
            return true;
        } else {
            return false;
        }
    }
    public function getLasId(){
        return $id=Libros::find()
            ->select('id')
            ->orderBy(['id' =>SORT_DESC])
            ->limit(1)
            ->one();
    }
    public function  editModel($model){
        $id = Libros::getLasId()->id +1;
        $model->name = $id.'.jpg';
        return $model;

    }

}

controllers/LibrosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Libros;
use app\models\Autores;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * LibrosController implements the CRUD actions for Libros model.
 */
class LibrosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Libros::find(),
            'pagination' => [
                'pageSize' => 4
            ]

        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionList()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Libros::find(),
            'pagination' => [
                'pageSize' => 4
            ]

        ]);

        return $this->render('detail', [
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionCreate()
    {
        $model = new Libros();

        if ($model->load(Yii::$app->request->post())) {
            $model->portada = UploadedFile::getInstance($model, 'portada');
            if ($model->portada == NULL){
                $model->validate();
                $model->save();
                return $this->redirect(['show2', 'id' => $model->id]);
            }else{
                if ($model->upload()) {
                    Libros::editModel($model->portada);
                    $model->portada = $model->portada->name;
                    $model->validate();
                    $model->save();
                    return $this->redirect(['show2', 'id' => $model->id]);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,

        ]);
    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->portada = UploadedFile::getInstance($model, 'portada');
            if ($model->portada == NULL){
                $model->save();
                return $this->redirect(['show2', 'id' => $model->id]);
            }else{
                if ($model->uploadid($id)) {
                    Libros::editModel($model->portada);
                    $model->portada = $id .'.jpg';
                    $model->save();
                    return $this->redirect(['show2', 'id' => $model->id]);
                }
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    protected function findModel($id)
    {
        if (($model = Libros::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    public function actionCrud()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Libros::find(),
            'pagination' => [
                'pageSize' => 4
            ]
        ]);
        return $this->render('crudLibros', [
            'dataProvider' => $dataProvider
        ]);
    }
    public function actionShow($id)
    {
        $model = $this->findModel($id);

        $autor = Autores::find()
            ->select('nombre')
            ->where(['id' => $model['autor_id']])
            ->asArray()
            ->one();

        return $this->render('full_detail', [
            'model' => $model,
            'nombreAutor' => $autor['nombre']
        ]);
    }
    public function actionShow2($id)
    {

        $libros=Libros::find()
            ->where(['id' => $id])->one();

        $autor = Libros::getNombreAutor($libros->autor_id);

        return $this->render("detail_libro",[
            "model"=>$libros,
            'nombre' =>$autor->nombre
        ]);
    }
}

views/libros/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Libros */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="libros-form">

    <div class="row col-lg-6">
        <?php $form = ActiveForm::begin([
            'options' => [
                'enctype' => 'multipart/form-data',
                'validateOnSubmit' => true,
            ]]) ?>

        <?php
            if($model->id != NULL){
                echo $form->field($model, 'id')->textInput(['maxlength' => true, 'disabled' => 'disabled']);
            }
        ?>

        <?= $form->field($model, 'nombre')->textInput(['maxlength' => true, 'placeholder' => 'Introduce un titulo']) ?>

        <?= $form->field($model, 'editorial')->textInput(['maxlength' => true, 'placeholder' => 'Introduce una editorial']) ?>

        <?= $form->field($model, 'autor_id')->dropDownList(
            $listaAutores,
            ['prompt'=>'Selecciona uno ...']
        );
        ?>

        <?= $form->field($model, 'portada')->fileInput(['class' => 'btn btn-default btn-file']) ?>

        <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
    <div class="row col-lg-6">
        <?php if($model->id != NULL){
            if($model->portada == NULL ){
                $url = $model->getImageUrl(0);
            }else{
                $url = $model->getImageUrl($model->id);
            }
            ?>
            <div class="col-md-12">
                <div class="thumbnail">
                    <?= Html::img($url, ['width'=>'300px','class' =>'img-responsive']); ?>
                </div>
            </div>
            <br>
            <?php
        }
        ?>
    </div>

</div>

views/libros/autor.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;


/* @var $this yii\web\View */
$this->title = 'Autores';
$this->params['breadcrumbs'][] = $this->title;
//var_dump($autor);
//exit;
?>
<div class="autores-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'nombre',
            [
                'header' => 'Foto',
                'format'=>'html',
                'value' => function ($model) {
                    $url = $model->getImageUrl($model->id);
                    return Html::img($url, ['width'=>'80','height'=>'100','display' =>'block', 'margin' =>'auto']);
                }
            ],
        ],
    ]); ?>


</div>

views/libros/create.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Autores;


/* @var $this yii\web\View */
/* @var $model app\models\Libros */

$autores=Autores::find()->all();
$listAutores=ArrayHelper::map($autores,'id','nombre');

$this->title = 'Agregar Libro';
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['crud']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="libros-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'listaAutores' =>$listAutores
    ]) ?>

</div>

views/libros/crudLibros.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
$this->title = 'Obras';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="autores-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nuevo Libro', ['libros/create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'pager' => [
            'firstPageLabel' => 'Primera',
            'lastPageLabel'  => 'Última'
        ],
        'layout' => "{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'nombre',
            [
                'header' => 'Foto',
                'format'=>'html',
                'value' => function ($model) {
                    $url = $model->getImageUrl($model->id);
                    return Html::img($url, ['width'=>'80','height'=>'100','display' =>'block', 'margin' =>'auto']);
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/libros/detail.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Listado Obras Información';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="libros-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'pager' => [
            'firstPageLabel' => 'Primera',
            'lastPageLabel'  => 'Última'
        ],
        'layout' => "{pager}\n{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'editorial',
            'autor.nombre',
            ['class' => 'yii\grid\ActionColumn',
                'header' => 'Información',
                'template' => '{link}',

                'buttons' => [
                    'link' => function ($url,$model) {
                        $url = 'show?id=' . $model->id;
                        return Html::a('Ampliar Información', ['/libros/show', 'id'=>$model->id], ['class'=>'btn btn-danger']);
                    },
                ],
            ],
        ],
    ]); ?>


</div>

views/libros/detail_libro.php
<?php

/**
 * Created by IntelliJ IDEA.
 * User: chema
 * Date: 03/04/2019
 * Time: 16:55
 */
use yii\helpers\Html;
$url = $model->getImageUrl($model->id);

/* @var $this yii\web\View */

$this->title = 'Obra';

?>
<div class="site-index">
    <div class="jumbotron">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <div class="container">
        <h1></h1>
        <div class="row">
            <div class="col-md-9">
                <div class="thumbnail">
                    <?= Html::img($url, ['width'=>'300px',['class' => 'img-responsive img-thumbnail']]); ?>
                </div>
            </div>
            <div class="col-md-3">
                <div class="thumbnail">
                    <h3>Id : <?= $model->id ?></h3>
                    <hr>
                    <h3>Título : <?= $model->nombre ?></h3>
                    <hr>
                    <h3>Editorial : <?= $model->editorial ?></h3>
                    <hr>
                    <h3>Autor : <?= $nombre ?></h3>
                    <hr>
                    <h3>Portada Archivo : <?= $model->portada ?></h3>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

views/libros/full_detail.php
<?php

use yii\helpers\Html;
use app\models\Libros;
use app\models\Autores;

$urlLibro = Libros::getImageUrl($model['id']);
$urlAutor = Autores::getImageUrl($model['autor_id']);

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Obras Autor';
?>
<div class="libros-index">
    <div class="jumbotron"><h1><?= Html::encode($this->title) ?></h1></div>

    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="thumbnail">
                <?= Html::img($urlLibro, ['width'=>'300','display' =>'block', 'margin' =>'auto']);?>
                <div class="caption">
                    <h3>Título: <?= $model['nombre']; ?></h3>
                    <p>Editorial :<?= $model['editorial']; ?></p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="thumbnail">
                <?= Html::img($urlAutor, ['width'=>'300','display' =>'block', 'margin' =>'auto']);?>
                <div class="caption">
                    <h3>Autor: <?= $nombreAutor ?></h3>
                </div>
            </div>
        </div>
    </div>

</div>

views/libros/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Obras de Biblioteca';
?>
<div class="libros-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'pager' => [
            'firstPageLabel' => 'Primera',
            'lastPageLabel'  => 'Última'
        ],
        'layout' => "{items}\n{pager}",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'editorial',
            'autor.nombre',
            [
                'header' => 'Portada',
                'format'=>'html',
                'value' => function ($model) {
                    $url = $model->getImageUrl($model->id);
                    return Html::img($url, ['width'=>'80','height'=>'120','display' =>'block', 'margin' =>'auto']);
                }
            ],
        ],
    ]); ?>


</div>

views/libros/update.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Autores;


/* @var $this yii\web\View */
/* @var $model app\models\Libros */

$autores=Autores::find()->all();
$listAutores=ArrayHelper::map($autores,'id','nombre');

$this->title = 'Update Libros: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['crud']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="libros-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'listaAutores' =>$listAutores
    ]) ?>

</div>

views/libros/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Libros */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['crud']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="libros-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'editorial',
            'autor_id',
            'portada',
        ],
    ]) ?>

</div>